### ISSUE TITLE
Is there a way to not generate a new tag if a tag already exists for the commit being built?

### ISSUE THREAD

**Issue by rbcaixeta** [go-semantic-release/action#28]
Reasoning is: If build breaks after tag/release is generated and is re-run i'd like to not create a new tag if no code change was made when re-running the build.

Thank you.

**Comment by christophwitzko** [comment]
Hi @rbcaixeta, this is currently not possible because semantic-release is in charge of determining the next version number and is not aware of previous failing builds.
I personally create an empty commit to trigger a new release using`git commit -m 'fix: trigger release' --allow-empty`.

I hope this is helpful to you. 🙏 ☺️

**Comment by rbcaixeta** [comment]
Hi @christophwitzko.

It's less about being aware of previous builds or not, and more like, have an options like `allowMultipleTagsOnSameCommit: false` that if the current commit already have a tag on it, don't put another one.

I don't see much value on my commit `a0b1c2d3` having `v0.1.0` and `v0.1.1` on it... like I most likely don't want to generate a new tag if the commit already have a tag.
